### ISSUE TITLE
License description is not aligned

### ISSUE THREAD

**Issue by dstaesse** [girtel/Net2Plan#133]
The License description on the main page reads "As a consequence of this, you may use parts of Net2Plan or the complete package inside your own programs for free, can make money from them and do not have to disclose your code. Although, you are obliged to mention that you are using Net2Plan in your program."

This does not fit with the LPGL v3 license under which this program is distributed. LGPLv3 (and newer) is a license that is usually used for libraries that allows non-free programs to dynamically link with said library. The description above is more in line with an Apache 2.0, BSD (2 or 3 clause) or MIT license. Either the text or the license should be updated to avoid future conflicts.

**Comment by ppavon** [comment]
Dear Dimitri, Thanks for your comment, we will analyze it carefully, Pablo
