### ISSUE TITLE
Node panel: Boolean types' background is not colored with the state of the row

### ISSUE THREAD

**Issue by JayEsEm** [girtel/Net2Plan#189]
When applying a custom color to a row's background (such as red for disabled node) the boolean cells are not colored with this background color.

![screenshot from 2018-02-13 09-37-49](https://user-images.githubusercontent.com/16116005/36140509-c6a20c3a-10a1-11e8-8c72-f469eefe5737.png)

**Comment by JayEsEm** [comment]
Also applies to the link table (and possibly the rest of the tables)

**Comment by CFSNM** [comment]
Solved
