### ISSUE TITLE
Demand coloring over canvas needs a color for both origin and destination node.

### ISSUE THREAD

**Issue by JayEsEm** [girtel/Net2Plan#194]
When picking a demand, the origin and destination nodes are highlighted in green and cyan respectively. When multiple demands are picked, a third color should be chosen to show that a node received and emits demands at the same time.
![screenshot from 2018-02-13 12-21-21](https://user-images.githubusercontent.com/16116005/36147423-6ad072ae-10b8-11e8-830d-2d93b64136a4.png)

**Comment by CFSNM** [comment]
Done
