### ISSUE TITLE
Multicast demand table: Adding a multicast demand is too rudimentary

### ISSUE THREAD

**Issue by JayEsEm** [girtel/Net2Plan#196]
The dialog for multicast demand selection does not feel comfortable. It asks for the ID of the nodes at the same time that those IDs are not visible at all. Wrong inputs are not controlled, it throws an exception into the console.

**Comment by JayEsEm** [comment]
Same for Multicast trees, but in this case it asks for the index of a link which is more confusing.

**Comment by CFSNM** [comment]
Solved. Now there is a GUI more comfortable to use
