### ISSUE TITLE
Route table: View/Edit back-up route -> "Add" button throws a handled but not shown exception

### ISSUE THREAD

**Issue by JayEsEm** [girtel/Net2Plan#197]
Trying to add a new back up route can result in the following error:

Exception in thread "AWT-EventQueue-0" com.net2plan.interfaces.networkDesign.Net2PlanException: A backup route cannot have backup routes itself

Which is never told to the user. Making it seem that the add and view buttons do nothing.

![screenshot from 2018-02-13 12-36-50](https://user-images.githubusercontent.com/16116005/36147980-9748436e-10ba-11e8-84f6-04935bb770e1.png)

**Comment by CFSNM** [comment]
Seem to be solved because of new table hierarchy model
