### ISSUE TITLE
Node IDs hidden in snapshots

### ISSUE THREAD

**Issue by JayEsEm** [girtel/Net2Plan#29]
In the resulting image of the snapshot function, the nodes Ids are highlighted with a white square. Making it impossible to distinguish one from the other.
![snapshot_example](https://cloud.githubusercontent.com/assets/16116005/20879812/b0d863cc-bad5-11e6-8070-8f0f5b424224.png)

**Comment by CFSNM** [comment]
I have made some photos and the nodes appear correctly.

**Comment by CFSNM** [comment]
Removing the index number from each node solves this problem
