### ISSUE TITLE
CPU time not shown well in Online simulation

### ISSUE THREAD

**Issue by ppavon** [girtel/Net2Plan#32]
It shows CPU time as the time between simulation start and simulation end when it pops up "Simulation Finished", but when you click OK it 'updates' to show the time between simulation start and click time.

Easy to reproduce: run ~100 events, it will finish in <1 sec, but wait a bit to click OK and it will then show ~10 sec.

The Simulation Information table in the Simulation Report tab shows the correct CPU time.

**Comment by JayEsEm** [comment]
The bug has been tested in the 0.4.2, 0.4.2.1 and the developer version of Net2Plan but has not been able to be reproduced in any of these. For the time being, this bug is not present in Net2Plan.
