### ISSUE TITLE
Naming a Layer does not work properly

### ISSUE THREAD

**Issue by xWampa** [girtel/Net2Plan#55]
On "View/Edit Network state > Layers > Name"

As soon as you type one character it jumps out to the box and you have to click again to keep Typing.

This is you have to name the layer character to character

**Comment by CFSNM** [comment]
We are working on fix several bugs. In a few days, maybe a week, we will upload a new Net2Plan 0.5.0 release with all these bugs fixed, included this one.

**Comment by CFSNM** [comment]
Solved
