### ISSUE TITLE
Right clicking on the topology canvas does not show up the pop up menu under linux

### ISSUE THREAD

**Issue by JayEsEm** [girtel/Net2Plan#56]
- Right clicking on the topology canvas in order to bring out the "Add node", "Add link"... popup does not seem to work under Linux. The popup menu does not appear at all.

**Comment by CFSNM** [comment]
Fixed

**Comment by israel-lugo** [comment]
Is there a chance that this fix could please be backported into the release? I'm using the 0.5.0 version from the release ZIP and even though I'm still learning to use the program, I imagine the right-click menu would probably be helpful.

**Comment by CFSNM** [comment]
We are fixing some bugs, included this one. 
In a few days, maybe a week, we will upload a new 0.5.0 release with all these bugs fixed.
