### ISSUE TITLE
Layers tab always shows the same layer (Linux)

### ISSUE THREAD

**Issue by israel-lugo** [girtel/Net2Plan#59]
I'm using the 0.5.0 release. Starting from a blank network, I've created a second layer, by going to the ``View/Edit network state -> Network`` tab and right-clicking on the ``Layer information`` panel.

I am now trying to change the new layer's name and routing type. However, when I go to the ``View/Edit network state -> Layers`` tab, the information shown is always about the first layer.

I tried selecting the second layer in the ``Layer information`` panel on the ``View/Edit network state -> Network`` tab, and then going to the ``Layers`` tab, but still the information shown is about the first layer.

Am I missing something? How can I configure the other layers?

**Comment by CFSNM** [comment]
Hello Israel, you should click in that button.
![image](https://cloud.githubusercontent.com/assets/22430652/23233537/710727fc-f94f-11e6-9843-992dd1eafeb8.png)

There, you will see something like that

![image](https://cloud.githubusercontent.com/assets/22430652/23233603/a4534212-f94f-11e6-9ee3-77ef603f3f86.png)

In the last column, you can choose a layer to make changes on it. (Active layer).

Now, in Layers tab you will see information about the active layer.

**Comment by israel-lugo** [comment]
You are absolutely correct. Thank you for taking the time to educate me. I did read the manual, but must not have understood this part well. Since I had already discovered that the right-click button isn't working on the canvas on Linux (issue #56), I thought there was some additional button or menu that wasn't showing.  I'll go ahead and close this, as it's not a bug.
