### ISSUE TITLE
OSM support does not seem to work under Linux

### ISSUE THREAD

**Issue by JayEsEm** [girtel/Net2Plan#64]
OSM cannot connect to the tile server while Net2Plan is running under Linux.
The result is a background filled with gray clocks.

![osm-issue](https://cloud.githubusercontent.com/assets/16116005/23360727/5e0f79a0-fced-11e6-8993-654a953a49c6.png)

**Comment by ppavon** [comment]
We have tested it and seems to work perfectly (maybe the OSM server was down?).
